apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: express
  name: basic-express-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - image: manojjahgirdar/gitops-lifecycle-tekton:vProd
        name: gitops-demo
        ports:
        - containerPort: 3000
